from projects.views.seller.registration.register import registerseller
from projects.views.seller.verification.verifyotp import verifyotpseller
from projects.views.seller.login.login import loginseller
from projects.views.seller.logout.logout import logoutseller
from projects.views.seller.homepage.home import homeseller
from projects.views.seller.profile.myprofile import sellerprofile
from projects.views.seller.itemactions.uploaditem import uploaditem
from projects.views.seller.itemactions.updateitem import updateitem
from projects.views.seller.itemactions.deleteitem import deleteitem
from projects.views.seller.items.viewdetails import myitemdetails
from projects.views.seller.items.myitems import myitems
from projects.views.seller.resetpassword.sendotp import sendsellerresetotp
from projects.views.seller.resetpassword.verifyotp import verifysellerresetotp
from projects.views.seller.resetpassword.newpassword import changesellerpassword
