# Generated by Django 4.2.5 on 2023-09-30 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_tag_project_voteratio_project_votetotal_review_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='featuredimage',
            field=models.ImageField(blank=True, default='user-default.png', null=True, upload_to=''),
        ),
    ]
