# Generated by Django 4.2.5 on 2023-10-01 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_featuredimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customername', models.CharField(max_length=150, unique=True)),
                ('customeremail', models.EmailField(max_length=254, unique=True)),
                ('customerpassword', models.CharField(max_length=128)),
            ],
        ),
    ]
