# Generated by Django 4.2.5 on 2023-10-04 16:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_remove_review_project_delete_project_delete_review_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('categoryname', models.CharField(max_length=200)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('featuredimage', models.ImageField(blank=True, default='', null=True, upload_to='')),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
                ('votetotal', models.IntegerField(blank=True, default=0, null=True)),
                ('voteratio', models.IntegerField(blank=True, default=0, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('tag', models.ManyToManyField(blank=True, to='projects.category')),
            ],
        ),
    ]
