# Generated by Django 4.2.5 on 2023-10-04 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_category_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sellername', models.CharField(max_length=150, unique=True)),
                ('selleremail', models.EmailField(max_length=254, unique=True)),
                ('sellerpassword', models.CharField(max_length=128)),
                ('sellerotp', models.CharField(blank=True, max_length=6, null=True)),
                ('seller_is_verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameField(
            model_name='item',
            old_name='description',
            new_name='itemdescription',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='featuredimage',
            new_name='itemfeaturedimage',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='title',
            new_name='itemtitle',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='uploaded',
            new_name='uploadedon',
        ),
        migrations.RemoveField(
            model_name='item',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='item',
            name='voteratio',
        ),
        migrations.RemoveField(
            model_name='item',
            name='votetotal',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
