# Generated by Django 4.2.5 on 2023-10-04 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_item_itemprice_item_itemquantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seller',
            old_name='sellername',
            new_name='storename',
        ),
    ]
