# Generated by Django 4.2.5 on 2023-10-04 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_rename_sellername_seller_storename'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seller',
            old_name='seller_is_verified',
            new_name='is_verified',
        ),
        migrations.RenameField(
            model_name='seller',
            old_name='sellerotp',
            new_name='otp',
        ),
    ]
