# Generated by Django 4.2.5 on 2023-10-16 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_alter_item_itemfeaturedimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='itemfeaturedimage',
            field=models.ImageField(blank=True, default='user-default.png', null=True, upload_to=''),
        ),
    ]
