# Generated by Django 4.2.5 on 2023-10-17 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_alter_item_itemfeaturedimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='seller',
        ),
        migrations.AlterField(
            model_name='item',
            name='itemfeaturedimage',
            field=models.ImageField(blank=True, default='', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.customer'),
        ),
    ]
