# Generated by Django 4.2.5 on 2023-10-17 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_remove_item_seller_alter_item_itemfeaturedimage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.seller'),
        ),
        migrations.AlterField(
            model_name='item',
            name='itemfeaturedimage',
            field=models.ImageField(blank=True, default='default_img.png', null=True, upload_to=''),
        ),
    ]
