# Generated by Django 4.2.6 on 2023-10-17 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_remove_item_seller_alter_item_itemfeaturedimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customername',
            field=models.CharField(max_length=150),
        ),
    ]
