# Generated by Django 4.2.6 on 2023-10-17 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_alter_customer_customername'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='storename',
            field=models.CharField(max_length=150),
        ),
    ]
