# Generated by Django 4.2.5 on 2023-10-17 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ManyToManyField(blank=True, to='projects.category'),
        ),
    ]
