# Generated by Django 4.2.6 on 2023-10-17 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_item_seller_alter_item_itemfeaturedimage'),
        ('projects', '0018_alter_seller_storename'),
    ]

    operations = [
    ]
