# Generated by Django 4.2.5 on 2023-10-17 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_item_category'),
        ('projects', '0019_merge_20231017_2017'),
    ]

    operations = [
    ]
