# Generated by Django 4.2.5 on 2023-10-19 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_merge_0019_item_category_0019_merge_20231017_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='categoryimage',
            field=models.ImageField(blank=True, default='default_img.png', null=True, upload_to=''),
        ),
    ]
