# Generated by Django 4.2.5 on 2023-10-21 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0024_customer_customerimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='sellerimage',
            field=models.ImageField(blank=True, default='user-default.png', null=True, upload_to=''),
        ),
    ]
