# Generated by Django 4.2.5 on 2023-10-21 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0025_seller_sellerimage'),
        ('projects', '0027_notification_is_read'),
    ]

    operations = [
    ]
