# Generated by Django 4.2.6 on 2023-10-21 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0025_seller_sellerimage'),
        ('projects', '0027_notification_is_read'),
    ]

    operations = [
    ]
