# Generated by Django 4.2.6 on 2023-10-21 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0028_merge_20231021_2217'),
        ('projects', '0028_merge_20231021_2239'),
    ]

    operations = [
    ]
