# Generated by Django 4.2.6 on 2023-10-22 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0030_favorite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite',
            old_name='user',
            new_name='customer',
        ),
    ]
