# Generated by Django 4.2.5 on 2023-12-16 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0037_item_original_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='original_price',
        ),
    ]
