# Generated by Django 4.2.5 on 2023-12-16 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0038_remove_item_original_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='original_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
