# Generated by Django 4.2.5 on 2023-12-16 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0039_item_original_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Cash on Delivery', 'Cash on Delivery'), ('Card', 'Card'), ('Not Selected', 'Not Selected')], default='Not Selected', max_length=20),
        ),
    ]
