# Generated by Django 4.2.5 on 2023-12-16 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0041_vouchercode_remove_item_discount_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='category',
        ),
        migrations.AlterField(
            model_name='vouchercode',
            name='vouchercode',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
