# Generated by Django 4.2.5 on 2024-01-12 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0043_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vouchercode',
            name='final_amount',
        ),
    ]
