# Generated by Django 4.2.5 on 2024-01-13 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0045_category_is_deleted_customer_is_deleted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='item',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='order',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='review',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='vouchercode',
            name='is_deleted',
        ),
    ]
