# Generated by Django 4.2.5 on 2024-01-14 13:56

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0048_remove_category_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='item',
            managers=[
                ('everything', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='orderitem',
            managers=[
                ('everything', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
