# Generated by Django 4.2.5 on 2024-01-14 14:21

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0049_alter_item_managers_alter_orderitem_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='notification',
            managers=[
                ('everything', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='notification',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
