# Generated by Django 4.2.5 on 2024-01-14 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0051_alter_favorite_managers_favorite_is_deleted'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='orderitem',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='is_deleted',
        ),
    ]
