# Generated by Django 4.2.5 on 2024-01-15 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0053_remove_notification_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='vouchercode',
            name='voucher_count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
