# Generated by Django 4.2.5 on 2024-01-15 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0054_vouchercode_voucher_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='vouchercode',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.customer'),
        ),
    ]
