# Generated by Django 4.2.5 on 2024-01-15 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0056_remove_vouchercode_customer_voucherusage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VoucherUsage',
        ),
    ]
